%YAML 1.2
---
name: SpaceTweet
description: an example for an ExoSphere application
version: 0.0.1

services:
  web:
    location: ./web-server
  users:
    location: ../exosphere-users-service
  tweets:
    location: ../tweets-service
